src/app/main.ts, src/app/services/info/audio.ts, src/app/services/info/battery.ts, src/app/services/info/bluetooth.ts, src/app/services/info/cpu.ts, src/app/services/info/filesystem.ts, src/app/services/info/graphics.ts, src/app/services/info/memory.ts, src/app/services/info/network.ts, src/app/services/info/os.ts
=> System Info

.github/workflows/ci.yml
Fixes missing mdns lib in windows, as this is now built with darwin and bonjour
=> Make with specific platform

package.json, src/index.ts, yarn.lock
=> Setup publishers

.github/workflows/deploy.yml, package.json
=> Deploy with publisher

.github/workflows/deploy.yml
=> Fix deploy server

README.md, package.json
=> Add Documentation

configuration/package.json, configuration/yarn.lock
=> Pin configuration deps

README.md
=> Add methods to endpoints table

package.json, src/index.ts
=> Access logs from menu

package.json
=> Add linux icon

src/services/index.ts, src/services/information/information.class.ts, src/services/open/open.class.ts, src/services/open/open.hooks.ts, src/services/open/open.service.ts
Opens a URL or file using the default application
=> Add open endpoint

src/services/information/information.class.ts
=> Add supported methods to information endpoint

src/index.ts
=> Fix log path

configuration/src/Settings/Item.tsx
=> Fix startup config change

configuration/package.json, configuration/src/App.tsx, configuration/src/Main.tsx, configuration/src/Settings/Item.tsx, configuration/src/Settings/Section.tsx, configuration/yarn.lock, package.json, src/index.ts, src/logger.ts, src/utils.ts, yarn.lock
=> Generated API Key

configuration/src/Main.tsx, configuration/src/Settings/Item.tsx, configuration/src/Settings/Section.tsx, configuration/src/Utils.tsx, src/index.ts, src/utils.ts
=> Add connection details to settings

src/api.ts
=> Only advertise mdns if there is a network interface

package.json, src/index.ts, yarn.lock
=> Fix shortcut generation

.github/workflows/deploy.yml, package.json
=> Deploy improvements

.github/workflows/deploy.yml
=> Version Bumping on Deploy

src/index.ts, src/logger.ts
=> Set logs path to user data directory

.github/workflows/deploy.yml
=> Fix deploy conditions

src/index.ts
=> Add UUID to MDNS info

src/api.ts
=> Add uuid to MDNS txt record

README.md, package.json, src/services/audio/audio.class.ts, yarn.lock
=> Add volume controls

README.md, src/services/index.ts, src/services/information/information.class.ts, src/services/notification/notification.class.ts, src/services/notification/notification.hooks.ts, src/services/notification/notification.service.ts
=> Create notification endpoint

src/channels.ts, src/services/audio/audio.class.ts, src/services/video/video.class.ts
=> Return 400 if file does not exist for media players

player/src/AudioPlayer.tsx
=> Fix audio player layout for long text

frontend/src/Configuration/Item.tsx, frontend/src/Main.tsx, frontend/src/Utils.tsx, src/index.ts
=> Redirect browser console output to main log

package.json, yarn.lock
=> Move required dev dependencies to main

package.json
=> Force ELECTRON_IS_DEV to false

frontend/src/Main.tsx, frontend/src/Player/AudioPlayer.tsx, frontend/src/Player/Player.tsx, frontend/src/Player/PlayerContainer.tsx, frontend/src/Player/Utils.tsx, frontend/src/Player/VideoPlayer.tsx, src/index.ts, src/player.ts
=> Media Player Playing Status

frontend/src/Player/AudioPlayer.tsx, frontend/src/Player/Player.tsx, frontend/src/Player/Utils.tsx, frontend/src/Player/VideoPlayer.tsx, src/api/media/dto/find-media.dto.ts, src/api/media/media.controller.ts, src/api/media/media.service.ts, src/player.ts
=> Media player Cover and Source

src/api/index.ts
=> Advertise WebSocket Port on MDNS

src/api/open/open.service.ts
=> Remove beep from open service

.github/workflows/ci.yml, frontend/src/Player/AudioPlayer.tsx, frontend/src/Player/Utils.tsx, frontend/src/Player/VideoPlayer.tsx, frontend/src/Utils.tsx, src/index.ts
=> Use branch on prettier stage and prettify automatically

src/api/app.module.ts, src/api/settings/dto/update-settings.dto.ts, src/api/settings/entities/settings.entity.ts, src/api/settings/settings.controller.spec.ts, src/api/settings/settings.controller.ts, src/api/settings/settings.module.ts, src/api/settings/settings.service.spec.ts, src/api/settings/settings.service.ts
=> Settings endpoint

src/api/media/media.service.ts
=> Fix 500 on missing source

src/api/index.ts, src/index.ts
=> Application info

frontend/src/Player/AudioPlayer.tsx, frontend/src/Player/VideoPlayer.tsx, src/index.ts, src/player.ts
=> Send cover/thumbnail to events

frontend/src/Player/Player.tsx, frontend/src/Player/Utils.tsx, src/api/index.ts, src/api/media/dto/find-media.dto.ts, src/api/media/media.controller.ts, src/api/media/media.service.ts, src/index.ts, src/player.ts
=> Serve cover as public file

src/api/processes/entities/processes.entity.ts, src/api/processes/processes.controller.ts, src/api/processes/processes.service.ts
=> Find process by name

frontend/src/Player/AudioPlayer.tsx
=> Make sure position slider is controlled

frontend/src/Player/Utils.tsx, frontend/src/Utils.tsx, src/api/index.ts, src/index.ts, src/rtc.ts
=> Cleanly exit app when quitting

package.json, src/api/app.module.ts, src/api/keyboard/dto/create-keyboard.dto.ts, src/api/keyboard/keyboard.controller.spec.ts, src/api/keyboard/keyboard.controller.ts, src/api/keyboard/keyboard.module.ts, src/api/keyboard/keyboard.service.spec.ts, src/api/keyboard/keyboard.service.ts, yarn.lock
Allows for keyboard keys to be pressed. List of [supported keys](http://robotjs.io/docs/syntax#keys)
Closes #368 
=> Add Keyboard endpoint to send keypresses

package.json, src/api/os/entities/os.entity.ts, src/api/os/os.service.ts, src/types/desktop-idle.d.ts, yarn.lock
=> Add idle time to OS endpoint

.github/workflows/ci.yml, .github/workflows/deploy.yml, README.md, package.json
=> Fix build and tests

.github/workflows/ci.yml, .github/workflows/deploy.yml, package.json
=> Windows build use windows to build

package.json, src/index.ts, yarn.lock
=> Remove auto updater

src/tray.ts
=> Add tray items

README.md, src/tray.ts
=> Add version check to tray

.github/workflows/codeql-analysis.yml, .github/workflows/deploy.yml, .github/workflows/labels.yml, .github/workflows/release-drafter.yml, package.json
=> Set version on branch

.github/workflows/ci.yml
=> CI Concurrency

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release-drafter.yml, .gitignore, nfpm.yaml, scripts/post-package.js, scripts/system-bridge.desktop, src/common.ts, src/main.ts, src/tray.ts
=> Linux Packages

scripts/installer.nsi, scripts/post-package.js
=> Create shortcuts with app icons for windows

src/common.ts, src/main.ts, tray/src/tray.ts
=> Use exec paths instead of working directory

.github/workflows/ci.yml, appdmg.json
=> Add create dmg step to CI

.github/workflows/deploy.yml
=> Create deploy workflow

nfpm.yaml, package.json, src/keyboard/dto/create-keyboard.dto.ts, src/keyboard/keyboard.service.ts
=> Add keyboard modifiers

src/keyboard/dto/create-keyboard.dto.ts, src/keyboard/keyboard.service.ts
=> Add ability to type text using keyboard endpoint

src/common.ts, src/information/entities/information.entity.ts, tray/src/tray.ts
=> Show correct version in tray and tooltip

nfpm.yaml, package.json, src/app.module.ts, src/usb/entities/usb.entity.ts, src/usb/usb.controller.spec.ts, src/usb/usb.controller.ts, src/usb/usb.module.ts, src/usb/usb.service.spec.ts, src/usb/usb.service.ts
=> Add USB endpoint

src/network/entities/network.entity.ts, src/network/network.service.ts
=> Add WiFi data to network endpoint

.github/workflows/ci.yml, appdmg.json, scripts/Info.plist, scripts/package.js, src/main.ts, tray/src/tray.ts
=> Mac OS App Bundle

frontend/src/Configuration/Configuration.tsx, frontend/src/Configuration/Item.tsx, nfpm.yaml, package.json, src/events.ts, src/main.ts, src/observer.ts
=> Create Event and Data Observer

.github/workflows/release-drafter.yml, frontend/package.json, nfpm.yaml, package.json, tray/package.json
=> Update all package files

.github/workflows/release-drafter.yml, frontend/src/Configuration/Configuration.tsx, src/common.ts, src/events/events.gateway.ts, src/mqtt.ts
=> Move MQTT into its own class and only connect on startup

frontend/package.json, nfpm.yaml, package.json, tray/package.json
=> Bump Version

.github/workflows/ci.yml
=> Only clean if not self-hosted

frontend/src/Configuration/Configuration.tsx
=> Add UUID to Settings

frontend/package.json, frontend/src/Common/Footer.tsx, frontend/src/Common/Header.tsx, frontend/src/Configuration/Configuration.tsx, frontend/src/Data/Data.tsx, frontend/src/Data/DataItems.tsx, frontend/src/Main.tsx, frontend/yarn.lock, src/events.ts, src/events/events.gateway.ts, src/observer.ts, tray/src/tray.ts, yarn.lock
Creates a frontend view for endpoints using the WebSocket to automatically update dynamic data.
Closes #573
=> Data Frontend

frontend/package.json, nfpm.yaml, package.json, tray/package.json
=> Update version to v2.3.0

frontend/package.json, frontend/src/Data/Data.tsx, nfpm.yaml, package.json, tray/package.json
=> Add Information endpoint to frontend

package.json, src/audio/audio.service.ts, src/audio/data/index.ts, src/audio/data/unix.ts, src/audio/data/win32.ts, src/audio/entities/audio.entity.ts, yarn.lock
Fix loudness import error, remove system-control and replace with own solution
Fixes #597
=> Fix loudness import error, remove system-control and replace with own solution

src/audio/audio.service.ts, src/audio/data/index.ts, src/observer.ts
=> Observer rework, add current audio to observer

frontend/package.json, nfpm.yaml, package.json, src/cpu/cpu.service.ts, src/graphics/entities/graphics.entity.ts, src/graphics/graphics.service.ts, tray/package.json, yarn.lock
=> Add hardware sensors to GPU endpoint

package.json, src/cpu/cpu.service.ts, src/graphics/graphics.service.ts, yarn.lock
=> Add filter to hardware sensor data gets

frontend/package.json, nfpm.yaml, package.json, src/cpu/cpu.service.ts, src/graphics/graphics.service.ts, tray/package.json
=> Allow for multiple GPU hardware sensors

frontend/package.json, nfpm.yaml, package.json, src/cpu/cpu.service.ts, tray/package.json
=> Fix clock speed to be MHz instead of GHz

src/cpu/cpu.service.ts
=> Allow for multiple CPU hardware sensors

frontend/src/Data/DataItems.tsx
=> Add loading data placeholder to frontend

frontend/src/Configuration/Configuration.tsx, src/observer.ts
=> Overhaul observer

src/common.ts, tray/src/tray.ts
=> Handle GitHub request errors (rate limiting) causing crash

.gitignore, src/api/app.module.ts, src/api/logs/logs.controller.spec.ts, src/api/logs/logs.controller.ts, src/api/logs/logs.module.ts, src/api/logs/logs.service.spec.ts, src/api/logs/logs.service.ts, src/logger.ts
=> Create logs endpoint

frontend/package.json, frontend/src/Logs/Logs.tsx, frontend/src/Main.tsx, nfpm.yaml, package.json, src/api/logs/logs.controller.ts, src/api/logs/logs.service.ts, tray/package.json, tray/src/tray.ts
=> Logs frontend

frontend/src/Configuration/Configuration.tsx, package.json, src/common.ts, src/events.ts, src/observer.ts, src/worker.ts, yarn.lock
=> Run observer tasks in worker

package.json, src/events.ts, src/observer.ts, yarn.lock
=> Add scheduler and start and stop ws handler

.github/workflows/ci.yml, src/components/api/app.module.ts, src/components/api/audio/audio.service.ts, src/components/api/audio/data/index.ts, src/components/api/bluetooth/bluetooth.service.ts, src/components/api/command/command.service.ts, src/components/api/cpu/cpu.service.ts, src/components/api/events/events.gateway.ts, src/components/api/graphics/graphics.service.ts, src/components/api/index.ts, src/components/api/logs/logs.service.ts, src/components/api/notification/notification.service.ts, src/components/api/os/os.service.ts, src/components/common.ts, src/components/events.ts, src/components/logger.ts, src/components/mqtt.ts, src/components/observer.ts, src/components/tray.ts, src/components/worker.ts, src/main.ts, tray/package.json, tray/src/components/common.ts, tray/src/components/logger.ts, tray/src/tray.ts
=> Logger class

.github/workflows/ci.yml, .github/workflows/deploy.yml, .gitignore, Dockerfile, Dockerfile.build, build.json, compose.yml, nfpm.yaml, rootfs/etc/services.d/app/run, src/components/api/httpAuth.guard.ts
=> Container use package

.github/workflows/ci.yml, .yarnclean, frontend/.yarnclean, package.json, tray/.yarnclean
=> Add yarn autoclean

README.md
=> Add Android companion app links

frontend/package.json, nfpm.yaml, package.json, src/components/api/filesystem/entities/filesystem.entity.ts, src/components/api/filesystem/filesystem.controller.ts, src/components/api/filesystem/filesystem.service.ts, tray/package.json
=> Add create file service

frontend/package.json, nfpm.yaml, package.json, src/components/api/cpu/cpu.service.ts, src/components/api/graphics/graphics.service.ts, src/components/api/index.ts, src/components/common.ts, src/index.ts, tray/package.json, tray/src/components/common.ts, tray/src/index.ts
=> Fix startup crashing

src/index.ts
=> Fix Windows tray crashes outside of installed dir

.github/workflows/deploy.yml
=> Replace release artifact if it exists

src/components/api/http-exception.filter.ts, src/components/api/index.ts, src/index.ts, tray/src/index.ts
=> Output uncaught exceptions to logger

package.json, src/components/api/os/entities/os.entity.ts, src/components/api/os/os.service.ts, src/types/desktop-idle.d.ts, yarn.lock
=> Remove desktop idle

package.json, yarn.lock
=> Downgrade PKG to fix package

package.json, src/components/api/audio/audio.service.ts, src/components/api/audio/data/index.ts, src/components/api/audio/data/unix.ts, src/components/api/audio/data/win32.ts, yarn.lock
=> Restore audio service

frontend/components/Common/Layout.tsx
=> Add prompt for when API key is missing

.github/workflows/build-macos.yml
=> Update MacOS build dmg script

src/components/api/processes/processes.controller.ts, src/components/api/processes/processes.service.ts
=> Split processes into multiple endpoints

.devcontainer/devcontainer.json, Dockerfile.dev
=> Add Devcontainer

frontend/components/Bridges/Edit.tsx, frontend/components/Bridges/Setup.tsx, src/components/api/bridges/bridges.controller.ts
=> Send to Bridge Setup (GUI) - Manual

frontend/components/Data/Data.tsx, src/components/api/events/entities/event.entity.ts, src/components/api/events/events.gateway.ts, src/components/api/processes/processes.controller.ts, src/components/api/processes/processes.service.ts, src/components/common.ts, src/components/events.ts, src/components/observer.ts, src/components/worker.ts
Closes #1103
Closes #1104
Relates to #951 
=> Observer - Only observe requested and specific data from websocket request

frontend/assets/entities/event.entity.ts, frontend/components/Data/Data.tsx, src/components/observer.ts, src/components/worker.ts
=> App Improvements

src/components/api/command/command.service.ts
=> Return success even when not waiting for result

frontend/components/Bridges/OpenOn.tsx, frontend/package.json, frontend/pages/app/bridges/openon.tsx, gui/systembridgegui/system_tray.py, nfpm.yaml, package.json
=> Send to -> Open URL On

gui/systembridgegui/system_tray.py
=> Show tray menu on clicked

src/components/events.ts, src/components/observer.ts
=> Run observer jobs one after the other

src/components/events.ts, src/components/observer.ts
=> Make scheduled tasks run synchronously

.github/workflows/build.yml, shared/requirements.txt
=> Workflows - Build

backend/systembridgebackend/WindowsSensors/HardwareMonitor.cs, backend/systembridgebackend/WindowsSensors/Nvidia.cs, backend/systembridgebackend/WindowsSensors/Program.cs, backend/systembridgebackend/WindowsSensors/Properties/AssemblyInfo.cs, backend/systembridgebackend/WindowsSensors/SystemBridgeWindowsSensors.csproj, backend/systembridgebackend/modules/sensors/__init__.py, backend/systembridgebackend/modules/sensors/update.py
=> NVIDIA Sensors

.github/workflows/build.yml, .vscode/launch.json, .vscode/tasks.json, backend/systembridgebackend/server/__init__.py, frontend/.vscode/settings.json, frontend/components/Common/HeaderLinks.tsx, frontend/pyproject.toml, frontend/setup.py, frontend/systembridgefrontend/__init__.py
=> Add frontend to systembridgefrontend package

backend/systembridgebackend/modules/gpu/__init__.py, backend/systembridgebackend/modules/gpu/update.py, backend/systembridgebackend/modules/update.py
=> GPU module

backend/systembridgebackend/modules/display/__init__.py, backend/systembridgebackend/modules/display/update.py, backend/systembridgebackend/modules/sensor/update.py, backend/systembridgebackend/modules/update.py, windowssensors/WindowsSensors/Nvidia.cs, windowssensors/WindowsSensors/Program.cs
=> Display module

.github/CONTRIBUTING.md, .github/workflows/build.yml, .github/workflows/deploy.yml
=> Workflows - Container

backend/systembridgebackend/server/media.py
=> Implement media upload

connector/systembridgeconnector/models/cpu.py, schemas/data/cpu.json, shared/systembridgeshared/models/cpu.py
Fix for linux (discovered on debian server)
=> Make cpu optionals optional

backend/systembridgebackend/modules/disk/update.py, backend/systembridgebackend/modules/display/update.py, backend/systembridgebackend/modules/gpu/update.py, backend/systembridgebackend/server/__init__.py, backend/systembridgebackend/server/media.py, backend/systembridgebackend/server/websocket.py, connector/systembridgeconnector/const.py, frontend/assets/entities/settings.entity.ts, frontend/assets/entities/types.entity.ts, frontend/components/Common/Theme.tsx, frontend/components/Settings/Item.tsx, frontend/components/Settings/ItemList.tsx, frontend/components/Settings/Settings.tsx, shared/systembridgeshared/common.py, shared/systembridgeshared/const.py, shared/systembridgeshared/database.py, shared/systembridgeshared/settings.py
=> Additional media directories

shared/systembridgeshared/models/data.py
=> Fix import of connector package instead of shared package

backend/systembridgebackend/server/media.py
=> Media - Add check that path is under specified base path

backend/systembridgebackend/server/__init__.py
Also adds name to OpenAPI spec at `/docs`
=> Add names to endpoints

frontend/assets/entities/event.entity.ts, frontend/components/Common/WebSocket.tsx, frontend/components/Player/Player.tsx
Related to #1784 
Not implemented in backend
=> Player Frontend - Connect, send status updates and handle events

backend/systembridgebackend/autostart/linux.py, backend/systembridgebackend/shortcut/linux.py
=> Fix missing directories - Linux

connector/systembridgeconnector/websocket_client.py, shared/systembridgeshared/websocket_client.py
Fixes GUI not closing from tray after changes from [3.3.1](https://github.com/timmo001/system-bridge/releases/tag/3.3.1)
=> Dont wait for response on exit backend

backend/systembridgebackend/server/notification.py, connector/systembridgeconnector/models/notification.py, frontend/components/Common/API.tsx, frontend/components/Common/Layout.tsx, frontend/pages/app/notification.tsx, gui/systembridgegui/window/notification.py, schemas/notification.json, shared/systembridgeshared/models/notification.py
https://github.com/timmo001/system-bridge/discussions/1822
=> Add actions to notifications

backend/systembridgebackend/server/media.py
https://github.com/timmo001/system-bridge/discussions/1825
=> Allow URLs for media playback

backend/systembridgebackend/gui.py, backend/systembridgebackend/server/__init__.py, backend/systembridgebackend/server/websocket.py
=> Allow GUI to be stopped by keyboard interrupt / SIGTERM

connector/systembridgeconnector/models/cpu.py, connector/systembridgeconnector/models/database_data_sensors.py, connector/systembridgeconnector/models/disk.py, connector/systembridgeconnector/models/display.py, connector/systembridgeconnector/models/network.py, schemas/data/cpu.json, schemas/data/disk.json, schemas/data/display.json, schemas/data/network.json, shared/systembridgeshared/models/cpu.py, shared/systembridgeshared/models/disk.py, shared/systembridgeshared/models/display.py, shared/systembridgeshared/models/network.py
Fixes issues with data being none at times / certain setups
=> Make data models optional

backend/systembridgebackend/modules/cpu/__init__.py, backend/systembridgebackend/modules/cpu/update.py, connector/systembridgeconnector/models/cpu.py, schemas/data/cpu.json, shared/systembridgeshared/models/cpu.py
=> Add CPU Power

backend/systembridgebackend/modules/display/update.py, backend/systembridgebackend/modules/gpu/update.py
=> Make sure display and gpus are not 0 before updating

backend/systembridgebackend/server/__init__.py, backend/systembridgebackend/server/api.py, backend/systembridgebackend/server/power.py, shared/systembridgeshared/common.py, shared/systembridgeshared/update.py
=> Fix event loop error

backend/systembridgebackend/server/__init__.py
=> Fxi loop error from calls in server

connector/requirements.txt
=> Fix connector conflict on homeassistant 2023.1.0.devx

connector/systembridgeconnector/websocket_client.py
=> Dont close session in connector

.vscode/settings.json, windowssensors/WindowsSensors/Properties/AssemblyInfo.cs, windowssensors/WindowsSensors/SystemBridgeWindowsSensors.csproj, windowssensors/WindowsSensors/SystemBridgeWindowsSensors.sln, windowssensors/WindowsSensors/packages.config
=> Upgrade WindowsSensors to .NET 7

connector/systembridgeconnector/models/battery.py, connector/systembridgeconnector/models/cpu.py, connector/systembridgeconnector/models/data.py, connector/systembridgeconnector/models/disk.py, connector/systembridgeconnector/models/display.py, connector/systembridgeconnector/models/generic.py, connector/systembridgeconnector/models/gpu.py, connector/systembridgeconnector/models/media.py, connector/systembridgeconnector/models/memory.py, connector/systembridgeconnector/models/network.py, connector/systembridgeconnector/models/request.py, connector/systembridgeconnector/models/response.py, connector/systembridgeconnector/models/sensors.py, shared/systembridgeshared/models/battery.py, shared/systembridgeshared/models/data.py, shared/systembridgeshared/models/disk.py, shared/systembridgeshared/models/display.py, shared/systembridgeshared/models/generic.py, shared/systembridgeshared/models/gpu.py, shared/systembridgeshared/models/media.py, shared/systembridgeshared/models/memory.py, shared/systembridgeshared/models/network.py, shared/systembridgeshared/models/request.py, shared/systembridgeshared/models/response.py, shared/systembridgeshared/models/sensors.py
=> Fix extra properties

Dockerfile, requirements_docker.txt
=> Use requirements file in dockerfile

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs
=> Notifications rework

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/src/resources.rs
=> Handle ctrl-c

src-tauri/src/main.rs
=> Write current version to a file for later use from the backend

requirements_linux.txt, requirements_windows.txt
https://github.com/timmo001/system-bridge-backend/releases/tag/4.2.0
=> Update backend to 4.2.0

requirements_linux.txt, requirements_windows.txt
https://github.com/timmo001/system-bridge-frontend/releases/tag/4.0.3
=> Update systembridgefrontend to 4.0.3

requirements_linux.txt, requirements_windows.txt
https://github.com/timmo001/system-bridge-backend/releases/tag/4.2.2
=> Update systembridgebackend to 4.2.2

data/module/gpus/gpus_darwin.go
The fields from the `system_profiler` command are a bit different. i've adapted the code to extract the available. For future reference this is the output with the internal display and two additional displays plugged in on an M3 Apple Silicon Chip
```json
> system_profiler SPDisplaysDataType -json
{
"SPDisplaysDataType" : [
{
"_name" : "Apple M3 Pro",
"spdisplays_mtlgpufamilysupport" : "spdisplays_metal3",
"spdisplays_ndrvs" : [
{
"_name" : "DELL U2722DE",
"_spdisplays_display-product-id" : "4231",
"_spdisplays_display-serial-number" : "4254554c",
"_spdisplays_display-vendor-id" : "10ac",
"_spdisplays_display-week" : "14",
"_spdisplays_display-year" : "2022",
"_spdisplays_displayID" : "2",
"_spdisplays_pixels" : "2560 x 1440",
"_spdisplays_resolution" : "2560 x 1440 @ 60.00Hz", …
```
=> Fix darwin GPU module

data/module/gpus/gpus_windows.go
This should make sure, that `gpus` are always an array of objects. When only one GPU was available, the list got simplified to a plain object
=> Ensure GPUs are always an array

data/module/system.go
Just a small typo fix to interpolate the log template
=> Use log formatter to print error message

backend/backend.go
When you try to start an additional instance for example and the server can't bind to the port we now get
```
2025/05/06 20:41:40 ERRO Server error caused shutdown: err="listen tcp 0.0.0.0:9170: bind: address already in use"
```
=> feat: allow application to stop when webserver can't start

backend/websocket/handlers.go
I just merged `handleMessages` and `HandleMessage` and removed the duplicate JSON parsing.
Additionally removed:
- `HandleClose`
- `HandleError`
because they weren't referenced anywhere
=> avoid parsing json a second time and merge function

data/module/cpu.go
Because we itroduced a context in the Updater interface we can now call the context aware functions from gopsutil in the CPU module
=> CPU Module: call functions with context

data/module/system.go, data/module/system/system_linux.go, data/module/system/system_other.go, types/system.go
=> Add power usage support via corsair rmi sensors in linux

backend/backend.go
Add /api/health endpoint that returns system health status including:
- Status: 'healthy'
- Timestamp: Current RFC3339 timestamp
- Version: Current application version
=> Add health check endpoint

backend/backend.go, backend/http/media.go
Implement /api/media/file/data from 4.x.x
=> Add media file data endpoint
